# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Moving in to terraform folder
        run: cd terraform
      # Download terraform 
      - name: Download Terraform in github VM
        run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        run: wget -O- https://apt.releases.hashicorp.com/gpg | \
             gpg --dearmor | \
             sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        run: gpg --no-default-keyring \
             --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
             --fingerprint
        run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \  
             https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
             sudo tee /etc/apt/sources.list.d/hashicorp.list
        run: sudo apt update
        run: sudo apt-get install terraform

        run: terraform init 
        run: terraform apply --auto-approve
